name: .NET

on:
  push:
    branches: ["main"]

jobs:
  pipeline:
    strategy: 
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x 

      - name: Run App
        run: dotnet run -c Release
        working-directory: ConsoleApp1